/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/b_student_2_lvl_8_skinning_fix.gltf
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import startAnimation from '../helpers/startAnimation';

/*
eslint-disable react/no-unknown-property
*/
const BStudent = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(process.env.PUBLIC_URL+'/b_student_2_lvl_8_skinning_fix.gltf');
  const { actions, names } = useAnimations(animations, group);

  // eslint-disable-next-line consistent-return
  useEffect(() => {
    startAnimation(actions, names);
  }, [actions, names]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='ARMA_b_student_2_lvl_8' position={[0.803, 0, 1.454]} rotation={[Math.PI, -1.17, Math.PI]}>
          <primitive object={nodes.pelvis} />
          <skinnedMesh
            castShadow
            name='MESH_b_student_2_lvl_8'
            geometry={nodes.MESH_b_student_2_lvl_8.geometry}
            material={materials['Texture_capibara.005']}
            skeleton={nodes.MESH_b_student_2_lvl_8.skeleton}
          />
          <group name='MESH_shirt'>
            <skinnedMesh name='Plane007' geometry={nodes.Plane007.geometry} material={materials.shirt} skeleton={nodes.Plane007.skeleton} />
            <skinnedMesh name='Plane007_1' geometry={nodes.Plane007_1.geometry} material={materials.buttonss} skeleton={nodes.Plane007_1.skeleton} />
          </group>
        </group>
        <group name='ARMA_book' position={[-1.22, 0, -0.366]} rotation={[0, 0.626, 0]}>
          <primitive object={nodes.root} />
          <group name='MESH_book_red'>
            <skinnedMesh castShadow name='Plane012' geometry={nodes.Plane012.geometry} material={materials.red} skeleton={nodes.Plane012.skeleton} />
            <skinnedMesh castShadow name='Plane012_1' geometry={nodes.Plane012_1.geometry} material={materials.pages} skeleton={nodes.Plane012_1.skeleton} />
          </group>
        </group>
        <group name='MESH_book_purple' position={[0.432, 0.118, -0.749]} rotation={[0, 0.256, -1.558]} scale={[1.804, 1, 1]}>
          <mesh castShadow name='Plane014' geometry={nodes.Plane014.geometry} material={materials.purle} />
          <mesh castShadow name='Plane014_1' geometry={nodes.Plane014_1.geometry} material={materials.white} />
        </group>
        <group name='MESH_book_green' position={[1.053, 0.348, -0.72]} rotation={[Math.PI, 0.908, 1.583]} scale={[1.527, 0.612, 0.612]}>
          <mesh castShadow name='Plane015' geometry={nodes.Plane015.geometry} material={materials.green} />
          <mesh castShadow name='Plane015_1' geometry={nodes.Plane015_1.geometry} material={materials.white} />
        </group>
      </group>
    </group>
  );
};

export default BStudent;

useGLTF.preload('/b_student_2_lvl_8_skinning_fix.gltf');
